### ISSUE TITLE
Crash regarding Zombie Hands in 1.12 version

### ISSUE THREAD

**Issue by darthvader45** [crazysnailboy/Halloween#2]
Apparently there's a ticking entity crash regarding Zombie Hands, supposedly referencing the getFire and unearthMe lines.  Possibly having to do with unearthing zombie hands in the daytime.  Any chance this could get fixed?
```

---- Minecraft Crash Report -------- Minecraft Crash Report ----
WARNING: coremods are present:Contact their authors BEFORE contacting forge
// I bet Cylons wouldn't have this problem.
Time: 8/6/17 1:37 PMDescription: Ticking entity
net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: field_70151_c at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:107) at net.crazysnailboy.mods.halloween.util.ReflectionUtils.getDeclaredField(ReflectionUtils.java:46) at net.crazysnailboy.mods.halloween.entity.monster.EntityZombieHands.getFire(EntityZombieHands.java:229) at net.crazysnailboy.mods.halloween.entity.monster.EntityZombieHands.unearthMe(EntityZombieHands.java:175) at net.crazysnailboy.mods.halloween.entity.monster.EntityZombieHands.func_70636_d(EntityZombieHands.java:99) at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2163) at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388) at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:46) at net.crazysnailboy.mods.halloween.entity.monster.EntityZombieHands.func_70071_h_(EntityZombieHands.java:79) at net.minecraft.world.World.func_72866_a(World.java:1976) at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833) at net.minecraft.world.World.func_72870_g(World.java:1939) at net.minecraft.world.World.func_72939_s(World.java:1753) at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) at java.lang.Thread.run(Thread.java:745)Caused by: java.lang.NoSuchFieldException: field_70151_c at java.lang.Class.getDeclaredField(Class.java:2062) at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:98) ... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Server threadStacktrace: at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:107) at net.crazysnailboy.mods.halloween.util.ReflectionUtils.getDeclaredField(ReflectionUtils.java:46) at net.crazysnailboy.mods.halloween.entity.monster.EntityZombieHands.getFire(EntityZombieHands.java:229) at net.crazysnailboy.mods.halloween.entity.monster.EntityZombieHands.unearthMe(EntityZombieHands.java:175) at net.crazysnailboy.mods.halloween.entity.monster.EntityZombieHands.func_70636_d(EntityZombieHands.java:99) at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2163) at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388) at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:46) at net.crazysnailboy.mods.halloween.entity.monster.EntityZombieHands.func_70071_h_(EntityZombieHands.java:79) at net.minecraft.world.World.func_72866_a(World.java:1976) at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833) at net.minecraft.world.World.func_72870_g(World.java:1939)
-- Entity being ticked --Details: Entity Type: halloween:zombiehands (net.crazysnailboy.mods.halloween.entity.monster.EntityZombieHands) Entity ID: 2214 Entity Name: entity.zombiehands.name Entity's Exact location: 297.34, 46.23, 290.56 Entity's Block location: World: (297,46,290), Chunk: (at 9,2,2 in 18,18; contains blocks 288,0,288 to 303,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511) Entity's Momentum: -0.11, -0.38, 0.03 Entity's Passengers: [] Entity's Vehicle: ~~ERROR~~ NullPointerException: nullStacktrace: at net.minecraft.world.World.func_72939_s(World.java:1753) at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
-- Affected level --Details: Level name: New World--- All players: 1 total; [EntityPlayerMP['KooplissKoopa'/396, l='New World---', x=285.34, y=70.58, z=295.32]] Chunk stats: ServerChunkCache: 1559 Drop: 0 Level seed: 4051717160324135626 Level generator: ID 00 - default, ver 1. Features enabled: true Level generator options: Level spawn location: World: (212,64,204), Chunk: (at 4,4,12 in 13,12; contains blocks 208,0,192 to 223,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511) Level time: 698 game time, 698 day time Level dimension: 0 Level storage version: 0x04ABD - Anvil Level weather: Rain time: 34416 (now: false), thunder time: 43806 (now: false) Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: trueStacktrace: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) at java.lang.Thread.run(Thread.java:745)
-- System Details --Details: Minecraft Version: 1.12 Operating System: Windows 7 (amd64) version 6.1 Java Version: 1.8.0_25, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 350717144 bytes (334 MB) / 814256128 bytes (776 MB) up to 3207856128 bytes (3059 MB) JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94 FML: MCP 9.40 Powered by Forge 14.21.1.2404 Optifine OptiFine_1.12_HD_U_C4 5 mods loaded, 5 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored UCHIJAAAA minecraft{1.12} [Minecraft] (minecraft.jar) UCHIJAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2404.jar) UCHIJAAAA forge{14.21.1.2404} [Minecraft Forge] (forge-1.12-14.21.1.2404.jar) UCHIJAAAA halloween{0.1} [Halloween Mod] (Halloween-1.12-0.1.jar) Loaded coremods (and transformers): GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread. Profiler Position: N/A (disabled) Player Count: 1 / 8; [EntityPlayerMP['KooplissKoopa'/396, l='New World---', x=285.34, y=70.58, z=295.32]] Type: Integrated Server (map_client.txt) Is Modded: Definitely; Client brand changed to 'fml,forge' OptiFine Version: OptiFine_1.12_HD_U_C4 Render Distance Chunks: 19 Mipmaps: 4 Anisotropic Filtering: 1 Antialiasing: 0 Multitexture: false Shaders: null OpenGlVersion: 4.5.0 NVIDIA 364.72 OpenGlRenderer: GeForce GT 750M/PCIe/SSE2 OpenGlVendor: NVIDIA Corporation CpuCount: 4
```

**Comment by crazysnailboy** [comment]
Hi,

You're using a very early version of the mod. Please update - [v0.1.10](https://github.com/crazysnailboy/Halloween/releases/tag/v1.12-0.1.10) is the latest - and this problem will no longer occur.

Can I ask where you found the link to v0.1?

**Comment by darthvader45** [comment]
This is from someone else, who I'm reporting this crash for.

**Comment by crazysnailboy** [comment]
OK, well it was fixed quite a while ago. Please ask the person who reported the bug to update.

The mod is now available on CurseForge: https://minecraft.curseforge.com/projects/no-holds-barred-halloween-mod

Thanks for reporting it though, and if your friend comes across any more bugs please let me know :)
